### ISSUE TITLE
Use timers for RHEL8+, not cron

### ISSUE THREAD

**Issue by glennmorris** [Q-Technologies/puppet-sysstat#13]
Hi,

In RHEL8 and later, sysstat is managed by a timer, not a cron job. Ref eg [here](https://access.redhat.com/solutions/5115491).
This module should use the timer method instead of adding a cron entry (which probably leads to double running of the data collection).

Thanks.

**Comment by mattqm** [comment]
Hi @glennmorris ,

I'm not in a position to do active development on this module anymore, but I will be more than happy to accept a pull request if you want to have a go.

Thanks

**Comment by glennmorris** [comment]
Hi; thanks for letting me know. I'm unlikely to work on this myself.

**Comment by parveenk27** [comment]
Hi @mattqm,

We are using this module and noticed that it does not support RHEL 8 and later releases. So, I have created MR https://github.com/Q-Technologies/puppet-sysstat/pull/14. Please review.

Thanks )

**Comment by mattqm** [comment]
Hi @parveenk27 , thanks for putting the PR together for us.  It has now been merged and I released the new version to the forge: https://forge.puppet.com/modules/qtechnologies/sysstat/readme.
