### ISSUE TITLE
Can not disable installpkg variable.

### ISSUE THREAD

**Issue by Death404** [Q-Technologies/puppet-sysstat#2]
Hello,

I was trying to use your module and we already have another module defining packages to install so we need to turn this feature off, however when you disable installpkg you get issues because of the chain to make the config file afterwards.

`Evaluation Error: Illegal relationship operand, can not form a relationship with an Undef Value.`

To reproduce add installpkg: 'no' to hiera

**Comment by mattqm** [comment]
Hi, I've put a fix in as 941d7b8.  Could you please test.  Thanks.

**Comment by Death404** [comment]
Hey, thanks for the quick response, im pulling this module through puppetforge, any way you can push another release there?

**Comment by mattqm** [comment]
Hi, I've published to the forge as 1.2.3
