### ISSUE TITLE
deprecated hiera version

### ISSUE THREAD

**Issue by sirinek** [Q-Technologies/puppet-sysstat#3]
The hiera.yaml file specifies version 4.

```2020-08-31T10:11:50.972-04:00 WARN  [qtp137873475-88] [puppetserver] Puppet /etc/puppetlabs/code/environments/nonprod/modules/sysstat/hiera.yaml: Use of 'hiera.yaml' version 4 is deprecated. It should be converted to version 5```

**Comment by mattqm** [comment]
Thanks, I've merged your changes in
